source 'https://rubygems.org'

gem 'rake'
gem 'rack'
gem 'rack-rewrite'
gem 'thin'

gem 'sprockets'
gem 'sprockets-sass'
gem 'compass'
gem 'compass-rails'
gem 'sass'
gem 'coffee-script'
gem 'zurb-foundation'
gem 'modernizr'
gem 'eco'
gem 'uglifier'